import {
  User,
  Department,
  Shift,
  Menu,
  MenuItem,
  Booking,
  AttendanceRecord,
  AttendanceSyncRun,
  AttendanceComparison,
  InventoryItem,
  InventoryTransaction,
  AuditLog,
  SystemSettings,
  QRTokenPayload,
  PermissionId,
  PermissionDefinition,
  RoleDefinition,
  MasanSupplier,
  DishIngredientRecipe,
  MasanPurchaseOrder,
  FeatureFlags
} from '../src/types';

// Helper for generating UUID-like random IDs
export function generateId(prefix = 'id'): string {
  return `${prefix}_${Math.random().toString(36).substring(2, 9)}_${Date.now().toString(36)}`;
}

// Current date formatted YYYY-MM-DD
export function getTodayDateString(): string {
  const now = new Date();
  return now.toISOString().split('T')[0];
}

// Format UTC to Vietnam Time string (Asia/Ho_Chi_Minh)
export function formatVietnamDateTime(isoString: string): string {
  try {
    const d = new Date(isoString);
    return d.toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });
  } catch {
    return isoString;
  }
}

// System Settings Store with Feature Flags
export const systemSettings: SystemSettings = {
  isQrCheckinEnabled: true,
  isAttendanceSyncEnabled: true,
  allowNegativeInventory: false,
  allowAdminCutoffOverride: true,
  costBasis: 'BOOKED',
  defaultCurrency: 'VND',
  timezone: 'Asia/Ho_Chi_Minh',
  canteenName: 'Nhà Ăn NETCO Post - Trụ Sở Chính (Màn Hình IPC)',
  featureFlags: {
    enableWeeklyBooking: true,
    enableBOMForecasting: true,
    enableDepartmentBooking: true,
    enableGuestBooking: true,
    enableAttendanceSync: true,
    enableMasterDishCatalog: true,
    enableKioskQrCheckin: true,
    enableInventoryAndSuppliers: true,
    enableMealRatingFeedback: true,
    enableDietaryPreference: true,
  },
};

// Departments Store
export const departments: Department[] = [
  {
    id: 'dept_it',
    code: 'IT-DEV',
    name: 'Phòng Công Nghệ Thông Tin',
    representativeUserId: 'usr_rep_it',
    totalEmployees: 5,
  },
  {
    id: 'dept_sales',
    code: 'SALES-MKT',
    name: 'Phòng Kinh Doanh & Tiếp Thị',
    representativeUserId: 'usr_rep_sales',
    totalEmployees: 4,
  },
  {
    id: 'dept_finance',
    code: 'FIN-ACC',
    name: 'Phòng Tài Chính & Kế Toán',
    representativeUserId: 'usr_emp_fin1',
    totalEmployees: 3,
  },
  {
    id: 'dept_hr_ga',
    code: 'HC-GA',
    name: 'Phòng Hành Chính - GA',
    representativeUserId: 'usr_hr',
    totalEmployees: 2,
  },
];

// System Permissions Catalog
export const systemPermissions: PermissionDefinition[] = [
  {
    id: 'MEAL_ORDER_SELF',
    name: 'Đặt & Hủy suất ăn cá nhân',
    category: 'Ăn uống',
    description: 'Cho phép nhân viên đăng ký hoặc hủy suất ăn cho chính mình trước giờ cut-off',
  },
  {
    id: 'MEAL_ORDER_BULK',
    name: 'Đặt suất ăn theo lô cho phòng ban',
    category: 'Ăn uống',
    description: 'Cho phép đại diện bộ phận đăng ký hàng loạt cho danh sách nhân viên',
  },
  {
    id: 'MEAL_ORDER_GUEST',
    name: 'Đăng ký suất ăn tiếp khách',
    category: 'Ăn uống',
    description: 'Cho phép tạo yêu cầu suất ăn cho khách công ty, ghi nhận mục đích và chi phí',
  },
  {
    id: 'MENU_CREATE',
    name: 'Biên soạn thực đơn',
    category: 'Bếp & Thực đơn',
    description: 'Cho phép bếp tạo thực đơn, định lượng dinh dưỡng, calo và gắn nhãn món chay',
  },
  {
    id: 'MENU_APPROVE',
    name: 'Phê duyệt / Từ chối thực đơn',
    category: 'Bếp & Thực đơn',
    description: 'Quyền duyệt thực đơn tuần/ngày của nhân sự trước khi mở đặt ăn',
  },
  {
    id: 'MENU_PUBLISH',
    name: 'Công bố thực đơn',
    category: 'Bếp & Thực đơn',
    description: 'Chuyển trạng thái thực đơn sang PUBLISHED để nhân viên bắt đầu đặt món',
  },
  {
    id: 'KITCHEN_PLAN',
    name: 'Kế hoạch sản xuất & Chia suất',
    category: 'Bếp & Thực đơn',
    description: 'Xem bảng tổng hợp số suất cần nấu của từng ca ăn và định lượng nguyên liệu',
  },
  {
    id: 'KITCHEN_INVENTORY',
    name: 'Quản lý kho nguyên vật liệu bếp',
    category: 'Bếp & Thực đơn',
    description: 'Nhập kho, xuất kho nấu ăn, kiểm kê tồn kho và cảnh báo hết hạn',
  },
  {
    id: 'KIOSK_SCAN_QR',
    name: 'Vận hành quét mã QR tại căng tin',
    category: 'Kiosk Căng tin',
    description: 'Dùng thiết bị quét mã QR động 60s để phát cơm cho nhân viên',
  },
  {
    id: 'KIOSK_MANUAL_CHECKIN',
    name: 'Xác nhận phát cơm thủ công',
    category: 'Kiosk Căng tin',
    description: 'Check-in thủ công khi nhân viên quên điện thoại hoặc mã QR lỗi (yêu cầu lý do)',
  },
  {
    id: 'HR_RECONCILIATION',
    name: 'Đối soát máy chấm công & Suất ăn',
    category: 'Nhân sự & Báo cáo',
    description: 'So sánh dữ liệu quẹt thẻ chấm công với số suất ăn đã đăng ký và check-in thực tế',
  },
  {
    id: 'HR_EXPENSE_REPORTS',
    name: 'Báo cáo chi phí phòng ban',
    category: 'Nhân sự & Báo cáo',
    description: 'Xem báo cáo chi phí tiền ăn, phân bổ ngân sách theo bộ phận và tỷ lệ no-show',
  },
  {
    id: 'SYSTEM_SETTINGS',
    name: 'Cấu hình hệ thống & Giờ ca ăn',
    category: 'Quản trị hệ thống',
    description: 'Thiết lập giờ bắt đầu/kết thúc ca, thời gian cut-off và cơ sở tính ngân sách',
  },
  {
    id: 'USER_MANAGEMENT',
    name: 'Quản lý hồ sơ nhân viên & người dùng',
    category: 'Quản trị hệ thống',
    description: 'Thêm mới, sửa thông tin, đặt lại trạng thái và gán phòng ban cho nhân sự',
  },
  {
    id: 'ROLE_PERMISSION_MANAGEMENT',
    name: 'Quản lý vai trò & Ma trận phân quyền',
    category: 'Quản trị hệ thống',
    description: 'Tạo vai trò mới, cấu hình quyền hạn chi tiết cho từng nhóm chức vụ',
  },
  {
    id: 'AUDIT_LOG_VIEW',
    name: 'Tra cứu nhật ký bảo mật Audit Trail',
    category: 'Quản trị hệ thống',
    description: 'Truy vết toàn bộ thao tác nhạy cảm đạt chuẩn bảo mật thông tin ISO-27001',
  },
];

// System Roles Definitions
export const roles: RoleDefinition[] = [
  {
    id: 'role_admin',
    roleKey: 'Administrator',
    name: 'Quản Trị Viên (Admin)',
    description: 'Toàn quyền điều hành, phân quyền, cấu hình hệ thống và kiểm tra an ninh.',
    isSystem: true,
    badgeColor: 'rose',
    permissions: [
      'MEAL_ORDER_SELF',
      'MEAL_ORDER_BULK',
      'MEAL_ORDER_GUEST',
      'MENU_CREATE',
      'MENU_APPROVE',
      'MENU_PUBLISH',
      'KITCHEN_PLAN',
      'KITCHEN_INVENTORY',
      'KIOSK_SCAN_QR',
      'KIOSK_MANUAL_CHECKIN',
      'HR_RECONCILIATION',
      'HR_EXPENSE_REPORTS',
      'SYSTEM_SETTINGS',
      'USER_MANAGEMENT',
      'ROLE_PERMISSION_MANAGEMENT',
      'AUDIT_LOG_VIEW',
    ],
  },
  {
    id: 'role_hr',
    roleKey: 'HR_GA',
    name: 'Hành Chính - GA (Hành chính GA)',
    description: 'Duyệt thực đơn, đối soát chấm công, kiểm soát chi phí và quản lý hồ sơ nhân viên.',
    isSystem: true,
    badgeColor: 'blue',
    permissions: [
      'MEAL_ORDER_SELF',
      'MENU_APPROVE',
      'MENU_PUBLISH',
      'HR_RECONCILIATION',
      'HR_EXPENSE_REPORTS',
      'USER_MANAGEMENT',
      'AUDIT_LOG_VIEW',
    ],
  },
  {
    id: 'role_kitchen',
    roleKey: 'Kitchen_Staff',
    name: 'Bếp Trưởng & Nhân Viên Bếp',
    description: 'Lên thực đơn dinh dưỡng, quản lý kho nguyên liệu và vận hành chuẩn bị suất ăn.',
    isSystem: true,
    badgeColor: 'amber',
    permissions: [
      'MEAL_ORDER_SELF',
      'MENU_CREATE',
      'MENU_PUBLISH',
      'KITCHEN_PLAN',
      'KITCHEN_INVENTORY',
      'KIOSK_SCAN_QR',
      'KIOSK_MANUAL_CHECKIN',
    ],
  },
  {
    id: 'role_dept_rep',
    roleKey: 'Department_Representative',
    name: 'Đại Diện Phòng Ban',
    description: 'Đại diện đặt ăn theo lô cho nhóm và làm thủ tục đăng ký suất ăn tiếp khách.',
    isSystem: true,
    badgeColor: 'blue',
    permissions: [
      'MEAL_ORDER_SELF',
      'MEAL_ORDER_BULK',
      'MEAL_ORDER_GUEST',
    ],
  },
  {
    id: 'role_employee',
    roleKey: 'Regular_Employee',
    name: 'Nhân Viên Tiêu Chuẩn',
    description: 'Đăng ký món ăn, xem thực đơn hàng ngày và sử dụng mã QR nhận cơm tại căng tin.',
    isSystem: true,
    badgeColor: 'slate',
    permissions: [
      'MEAL_ORDER_SELF',
    ],
  },
  {
    id: 'role_kiosk_operator',
    roleKey: 'QR_Checkin_Operator',
    name: 'Soát Vé Kiosk Căng Tin',
    description: 'Trực trạm quét QR tại cửa căng tin và xử lý các trường hợp quên điện thoại.',
    isSystem: true,
    badgeColor: 'emerald',
    permissions: [
      'KIOSK_SCAN_QR',
      'KIOSK_MANUAL_CHECKIN',
      'MEAL_ORDER_SELF',
    ],
  },
];

// Users Store
export const users: User[] = [
  {
    id: 'usr_admin',
    employeeCode: 'ADMIN001',
    name: 'Nguyễn Văn Quản Trị',
    email: 'admin@netcovn.com.vn',
    role: 'Administrator',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    phone: '0901 111 222',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: true,
    dietaryPreference: 'NONE',
    allergens: [],
    dietaryNote: 'Khẩu phần bình thường, ăn đúng giờ',
    joinedDate: '2022-03-15',
  },
  {
    id: 'usr_hr',
    employeeCode: 'GA001',
    name: 'Trần Thị Hành Chính GA',
    email: 'ga@netcovn.com.vn',
    role: 'HR_GA',
    departmentId: 'dept_hr_ga',
    departmentName: 'Phòng Hành Chính - GA',
    phone: '0902 333 444',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: true,
    dietaryPreference: 'LOW_CARB',
    allergens: ['Đậu phộng'],
    dietaryNote: 'Ưu tiên nhiều rau xanh, hạn chế cơm trắng',
    joinedDate: '2021-08-01',
  },
  {
    id: 'usr_chef',
    employeeCode: 'BEP001',
    name: 'Lê Văn Bếp Trưởng',
    email: 'chef@netcovn.com.vn',
    role: 'Kitchen_Staff',
    departmentId: 'dept_hr_ga',
    departmentName: 'Phòng Hành Chính - GA',
    phone: '0903 555 666',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
    dietaryPreference: 'NONE',
    allergens: [],
    dietaryNote: 'Ăn thử vị mẫu ca ăn',
    joinedDate: '2020-05-10',
  },
  {
    id: 'usr_rep_it',
    employeeCode: 'REP001',
    name: 'Vũ Hoàng (Đại diện IT)',
    email: 'rep.it@netcovn.com.vn',
    role: 'Department_Representative',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    phone: '0904 777 888',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
    dietaryPreference: 'NONE',
    allergens: ['Hải sản có vỏ'],
    dietaryNote: 'Dị ứng tôm cua biển',
    joinedDate: '2023-01-10',
  },
  {
    id: 'usr_rep_sales',
    employeeCode: 'REP002',
    name: 'Đỗ Mai (Đại diện Sales)',
    email: 'rep.sales@netcovn.com.vn',
    role: 'Department_Representative',
    departmentId: 'dept_sales',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    phone: '0905 999 000',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
    dietaryPreference: 'VEGETARIAN',
    allergens: [],
    dietaryNote: 'Thích dùng món chay rằm và mùng một',
    joinedDate: '2023-04-18',
  },
  {
    id: 'usr_emp_tuan',
    employeeCode: 'EMP001',
    name: 'Hoàng Minh Tuấn',
    email: 'tuan.hm@netcovn.com.vn',
    role: 'Regular_Employee',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    phone: '0912 345 678',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
    dietaryPreference: 'NONE',
    allergens: [],
    dietaryNote: 'Khẩu phần đầy đủ',
    joinedDate: '2023-06-01',
  },
  {
    id: 'usr_emp_lan',
    employeeCode: 'EMP002',
    name: 'Đinh Ngọc Lan',
    email: 'lan.dn@netcovn.com.vn',
    role: 'Regular_Employee',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    phone: '0913 456 789',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
    dietaryPreference: 'VEGETARIAN',
    allergens: ['Trứng'],
    dietaryNote: 'Ăn chay trường, không dùng trứng và mỡ động vật',
    joinedDate: '2023-09-15',
  },
  {
    id: 'usr_emp_duc',
    employeeCode: 'EMP003',
    name: 'Ngô Việt Đức',
    email: 'duc.nv@netcovn.com.vn',
    role: 'Regular_Employee',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    phone: '0914 567 890',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
    dietaryPreference: 'DIABETIC',
    allergens: [],
    dietaryNote: 'Ít đường, không uống nước ngọt',
    joinedDate: '2023-11-20',
  },
  {
    id: 'usr_emp_sales1',
    employeeCode: 'EMP004',
    name: 'Phan Bảo Hân',
    email: 'han.pb@netcovn.com.vn',
    role: 'Regular_Employee',
    departmentId: 'dept_sales',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    phone: '0915 678 901',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1534751516642-a171edd25218?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
  },
  {
    id: 'usr_emp_sales2',
    employeeCode: 'EMP005',
    name: 'Nguyễn Tấn Đạt',
    email: 'dat.nt@netcovn.com.vn',
    role: 'Regular_Employee',
    departmentId: 'dept_sales',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    phone: '0916 789 012',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
  },
  {
    id: 'usr_emp_fin1',
    employeeCode: 'EMP006',
    name: 'Bùi Thu Trang',
    email: 'trang.bt@netcovn.com.vn',
    role: 'Regular_Employee',
    departmentId: 'dept_finance',
    departmentName: 'Phòng Tài Chính & Kế Toán',
    phone: '0917 890 123',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
  },
  {
    id: 'usr_scanner',
    employeeCode: 'IPC001',
    name: 'Màn Hình IPC Nhà Ăn (Canteen Display)',
    email: 'ipc.canteen@netcovn.com.vn',
    role: 'QR_Checkin_Operator',
    departmentId: 'dept_hr_ga',
    departmentName: 'Phòng Hành Chính - GA',
    phone: '0918 901 234',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=150&auto=format&fit=crop&q=80',
    isMfaEnabled: false,
  },
];

// Shifts Store with strict Cut-off parameters
// Cố định 3 ca: Ca A (sáng), Ca B (trưa), Ca C (chiều/tối).
// Việc có thêm ca tăng ca hay không sẽ được quyết định sau.
export const shifts: Shift[] = [
  {
    id: 'shift_a',
    name: 'Ca A',
    code: 'CA_A',
    startTime: '06:30',
    endTime: '08:30',
    cutoffOrderMinutesBefore: 600, // Chốt đặt tối hôm trước (20:30)
    cutoffCancelMinutesBefore: 120, // Chốt hủy 2 tiếng trước
    checkinStartWindowMinutes: 30,
    checkinEndWindowMinutes: 30,
    isActive: true,
    orderCutoffDisplay: '20:30 (Hôm trước)',
    cancelCutoffDisplay: '04:30 (Cùng ngày)',
  },
  {
    id: 'shift_b',
    name: 'Ca B',
    code: 'CA_B',
    startTime: '11:30',
    endTime: '13:30',
    cutoffOrderMinutesBefore: 120, // Chốt đặt 09:30
    cutoffCancelMinutesBefore: 60,  // Chốt hủy 10:30
    checkinStartWindowMinutes: 30,
    checkinEndWindowMinutes: 30,
    isActive: true,
    orderCutoffDisplay: '09:30',
    cancelCutoffDisplay: '10:30',
  },
  {
    id: 'shift_c',
    name: 'Ca C',
    code: 'CA_C',
    startTime: '17:30',
    endTime: '19:30',
    cutoffOrderMinutesBefore: 150, // Chốt đặt 15:00
    cutoffCancelMinutesBefore: 90,  // Chốt hủy 16:00
    checkinStartWindowMinutes: 30,
    checkinEndWindowMinutes: 30,
    isActive: true,
    orderCutoffDisplay: '15:00',
    cancelCutoffDisplay: '16:00',
  },
];

// Seed Sample Menus
const today = getTodayDateString();
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const dayAfter = new Date(Date.now() + 172800000).toISOString().split('T')[0];

export const sampleDishes: MenuItem[] = [
  {
    id: 'dish_1',
    name: 'Cơm Sườn Nướng Mật Ong Rừng',
    description: 'Sườn heo ướp mật ong hoa vải nướng than hồng thơm lừng, kèm cơm tấm lá dứa & đồ chua giòn rụm.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
    isVegetarian: false,
    allergens: ['Đậu phộng (trong mỡ hành)'],
    calories: 680,
    category: 'Món chính',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_2',
    name: 'Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo',
    description: 'Phi lê cá hồi sốt chanh leo chua dịu, kèm khoai tây nghiền bơ sữa và măng tây áp chảo.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&auto=format&fit=crop&q=80',
    isVegetarian: false,
    allergens: ['Hải sản', 'Bơ sữa'],
    calories: 590,
    category: 'Món chính',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_3',
    name: 'Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)',
    description: 'Đậu phụ non chiên vàng sốt cùng nấm đông cô tươi, nấm rơm và mộc nhĩ thanh đạm.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=80',
    isVegetarian: true,
    allergens: ['Đậu nành'],
    calories: 420,
    category: 'Món chay',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_4',
    name: 'Gà Ta Kho Gừng Lá Chanh',
    description: 'Gà đồi thả vườn chặt miếng kho đậm đà thơm mùi gừng già và lá chanh tươi.',
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=500&auto=format&fit=crop&q=80',
    isVegetarian: false,
    allergens: [],
    calories: 540,
    category: 'Món chính',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_5',
    name: 'Canh Chua Cá Bông Lau Bạc Hà',
    description: 'Canh chua chuẩn vị Nam Bộ với cà chua, thơm, dọc mùng, giá đỗ và rau ngò gai.',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=80',
    isVegetarian: false,
    allergens: ['Hải sản'],
    calories: 180,
    category: 'Canh',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_6',
    name: 'Canh Hạt Sen Táo Đỏ Nấm Hương (Chay)',
    description: 'Canh chay thanh mát, bổ dưỡng, an thần nấu từ hạt sen Huế tươi và nấm tuyết.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=80',
    isVegetarian: true,
    allergens: [],
    calories: 140,
    category: 'Canh',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_7',
    name: 'Chè Long Nhãn Hạt Sen Tuyết Giáp',
    description: 'Món tráng miệng thanh tao giải nhiệt, ngọt dịu từ đường phèn thiên nhiên.',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&auto=format&fit=crop&q=80',
    isVegetarian: true,
    allergens: [],
    calories: 160,
    category: 'Tráng miệng',
    status: 'APPROVED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_admin',
    approvedByName: 'Nguyễn Văn Quản Trị',
    approvedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'dish_8',
    name: 'Bò Hầm Tiêu Xanh Rượu Vang Đà Lạt',
    description: 'Bắp bò hoa hầm mềm cùng sốt tiêu xanh cay nồng và rượu vang thơm nức, ăn kèm bánh mì bơ tỏi.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
    isVegetarian: false,
    allergens: ['Bơ sữa'],
    calories: 650,
    category: 'Món chính',
    status: 'PENDING_APPROVAL',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    createdAt: '2026-09-07T08:30:00.000Z',
  },
  {
    id: 'dish_9',
    name: 'Cơm Niêu Nấm Thập Cẩm Sốt Xì Dầu Sing (Chay)',
    description: 'Cơm niêu cháy giòn đáy thố đất, phủ nấm đùi gà, nấm hương, đậu bắp sốt xì dầu kiểu Singapore.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=80',
    isVegetarian: true,
    allergens: ['Đậu nành'],
    calories: 460,
    category: 'Món chay',
    status: 'PENDING_APPROVAL',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    createdAt: '2026-09-07T08:45:00.000Z',
  },
];

// Master Dish Catalog (Ngân hàng món ăn dùng chung chuẩn NETCO Meal)
export const masterDishes: MenuItem[] = [...sampleDishes];

export const menus: Menu[] = [
  {
    id: 'menu_today_lunch',
    date: today,
    shiftId: 'shift_b',
    title: 'Thực Đơn Trưa Cao Cấp - Bữa Cơm Doanh Nghiệp',
    description: 'Thực đơn tiêu chuẩn dinh dưỡng cân bằng năng lượng cho nhân viên văn phòng & sản xuất.',
    price: 45000,
    status: 'PUBLISHED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_hr',
    approvedByName: 'Trần Thị Nhân Sự',
    approvedAt: `${today}T08:00:00.000Z`,
    publishedAt: `${today}T08:05:00.000Z`,
    items: [sampleDishes[0], sampleDishes[1], sampleDishes[2], sampleDishes[4], sampleDishes[6]],
  },
  {
    id: 'menu_today_dinner',
    date: today,
    shiftId: 'shift_c',
    title: 'Thực Đơn Chiều Tối Năng Lượng',
    description: 'Các món xào kho nóng sốt phục vụ ca làm việc buổi tối & tăng ca.',
    price: 40000,
    status: 'PUBLISHED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_hr',
    approvedByName: 'Trần Thị Nhân Sự',
    approvedAt: `${today}T08:30:00.000Z`,
    publishedAt: `${today}T08:35:00.000Z`,
    items: [sampleDishes[3], sampleDishes[2], sampleDishes[5], sampleDishes[6]],
  },
  {
    id: 'menu_tomorrow_lunch',
    date: tomorrow,
    shiftId: 'shift_b',
    title: 'Thực Đơn Trưa Ngày Mai - Ẩm Thực Vùng Miền',
    description: 'Thực đơn đã được HR/GA phê duyệt sẵn sàng để nhân viên đăng ký trước.',
    price: 45000,
    status: 'PUBLISHED',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    approvedById: 'usr_hr',
    approvedByName: 'Trần Thị Nhân Sự',
    approvedAt: `${today}T14:00:00.000Z`,
    publishedAt: `${today}T14:10:00.000Z`,
    items: [sampleDishes[0], sampleDishes[3], sampleDishes[2], sampleDishes[4], sampleDishes[6]],
  },
  {
    id: 'menu_upcoming_pending',
    date: dayAfter,
    shiftId: 'shift_b',
    title: 'Thực Đơn Trưa Ngày Kia (Đang Chờ HR Duyệt)',
    description: 'Thực đơn do Bếp Trưởng soạn thảo gửi ban Nhân Sự xét duyệt định mức dinh dưỡng.',
    price: 48000,
    status: 'PENDING_APPROVAL',
    createdById: 'usr_chef',
    createdByName: 'Lê Văn Bếp Trưởng',
    items: [sampleDishes[1], sampleDishes[3], sampleDishes[2], sampleDishes[5]],
  },
];

// Bookings Store with initial seed data
export const bookings: Booking[] = [
  {
    id: 'book_001',
    bookingCode: 'BK-2026-0001',
    userId: 'usr_emp_tuan',
    userName: 'Hoàng Minh Tuấn',
    userEmployeeCode: 'EMP001',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    mealDate: today,
    shiftId: 'shift_b',
    shiftName: 'Ca B',
    menuId: 'menu_today_lunch',
    selectedItemIds: ['dish_1', 'dish_5', 'dish_7'],
    selectedItemNames: ['Cơm Sườn Nướng Mật Ong Rừng', 'Canh Chua Cá Bông Lau Bạc Hà', 'Chè Long Nhãn Hạt Sen Tuyết Giáp'],
    status: 'CONFIRMED',
    isGuest: false,
    priceSnapshot: 45000,
    bookedAt: `${today}T07:30:00.000Z`,
    bookedByUserId: 'usr_emp_tuan',
    bookedByName: 'Hoàng Minh Tuấn',
  },
  {
    id: 'book_002',
    bookingCode: 'BK-2026-0002',
    userId: 'usr_emp_lan',
    userName: 'Đinh Ngọc Lan',
    userEmployeeCode: 'EMP002',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    mealDate: today,
    shiftId: 'shift_b',
    shiftName: 'Ca B',
    menuId: 'menu_today_lunch',
    selectedItemIds: ['dish_3', 'dish_6', 'dish_7'],
    selectedItemNames: ['Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)', 'Canh Hạt Sen Táo Đỏ Nấm Hương (Chay)', 'Chè Long Nhãn Hạt Sen Tuyết Giáp'],
    status: 'CHECKED_IN',
    isGuest: false,
    priceSnapshot: 45000,
    bookedAt: `${today}T08:15:00.000Z`,
    checkedInAt: `${today}T11:45:10.000Z`,
    checkedInBy: 'Kiosk Canteen (SCAN001)',
    bookedByUserId: 'usr_emp_lan',
    bookedByName: 'Đinh Ngọc Lan',
  },
  {
    id: 'book_003',
    bookingCode: 'BK-2026-0003',
    userId: 'usr_emp_sales1',
    userName: 'Phan Bảo Hân',
    userEmployeeCode: 'EMP004',
    departmentId: 'dept_sales',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    mealDate: today,
    shiftId: 'shift_b',
    shiftName: 'Ca B',
    menuId: 'menu_today_lunch',
    selectedItemIds: ['dish_2', 'dish_5'],
    selectedItemNames: ['Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo', 'Canh Chua Cá Bông Lau Bạc Hà'],
    status: 'CONFIRMED',
    isGuest: false,
    priceSnapshot: 45000,
    bookedAt: `${today}T08:20:00.000Z`,
    bookedByUserId: 'usr_emp_sales1',
    bookedByName: 'Phan Bảo Hân',
  },
  {
    id: 'book_004',
    bookingCode: 'BK-2026-0004',
    userId: 'usr_rep_it',
    userName: 'Khách Đối Tác Công Nghệ AWS',
    userEmployeeCode: 'GUEST-01',
    departmentId: 'dept_it',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    mealDate: today,
    shiftId: 'shift_b',
    shiftName: 'Ca B',
    menuId: 'menu_today_lunch',
    selectedItemIds: ['dish_2', 'dish_7'],
    selectedItemNames: ['Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo', 'Chè Long Nhãn Hạt Sen Tuyết Giáp'],
    status: 'CONFIRMED',
    isGuest: true,
    guestName: 'Đoàn Chuyên Gia Giải Pháp Cloud AWS (3 người)',
    guestCount: 3,
    purpose: 'Tiếp đón đối tác thảo luận hạ tầng đám mây AI Studio',
    note: 'Yêu cầu phục vụ phòng VIP 2 nếu có',
    priceSnapshot: 45000,
    bookedAt: `${today}T08:45:00.000Z`,
    bookedByUserId: 'usr_rep_it',
    bookedByName: 'Vũ Hoàng (Đại diện IT)',
  },
];

// Seed Attendance Records (Máy chấm công)
export const attendanceRecords: AttendanceRecord[] = [
  {
    id: 'att_001',
    employeeCode: 'EMP001',
    employeeName: 'Hoàng Minh Tuấn',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    date: today,
    checkInTime: '08:12:45',
    machineId: 'ZKTECO_GATE_01',
    deviceId: 'DEV-HQ-L1',
  },
  {
    id: 'att_002',
    employeeCode: 'EMP002',
    employeeName: 'Đinh Ngọc Lan',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    date: today,
    checkInTime: '08:05:12',
    machineId: 'ZKTECO_GATE_01',
    deviceId: 'DEV-HQ-L1',
  },
  {
    id: 'att_003',
    employeeCode: 'EMP003',
    employeeName: 'Ngô Việt Đức',
    departmentName: 'Phòng Công Nghệ Thông Tin',
    date: today,
    checkInTime: '08:28:00',
    machineId: 'ZKTECO_GATE_01',
    deviceId: 'DEV-HQ-L1',
  },
  {
    id: 'att_004',
    employeeCode: 'EMP004',
    employeeName: 'Phan Bảo Hân',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    date: today,
    checkInTime: '08:15:30',
    machineId: 'ZKTECO_GATE_02',
    deviceId: 'DEV-HQ-L2',
  },
  {
    id: 'att_005',
    employeeCode: 'EMP005',
    employeeName: 'Nguyễn Tấn Đạt',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    date: today,
    checkInTime: '08:35:10',
    machineId: 'ZKTECO_GATE_02',
    deviceId: 'DEV-HQ-L2',
  },
];

// Attendance Sync Runs Store
export const attendanceSyncRuns: AttendanceSyncRun[] = [
  {
    id: 'sync_run_01',
    syncedAt: `${today}T09:00:00.000Z`,
    totalProcessed: 5,
    matchedEmployees: 5,
    discrepancyCount: 1, // Ngô Việt Đức đi làm nhưng chưa đặt cơm trưa!
    status: 'SUCCESS',
    triggeredBy: 'Automated Cron Job (09:00 UTC+7)',
    notes: 'Đồng bộ từ máy chấm công ZKTeco qua REST API Adapter thành công.',
  },
];

// Inventory Store
// Inventory Store - 100% Masan Group Ecosystem Policy
export const inventoryItems: InventoryItem[] = [
  // 1. Thịt & Trứng: 100% từ MML (Masan MEATLife)
  {
    id: 'inv_mml_01',
    sku: 'MML-SUON-HEO',
    name: 'Sườn Heo MEATDeli Chuẩn Mát (MML)',
    category: 'Thực phẩm tươi sống',
    unit: 'Kg',
    supplier: 'MML (Masan MEATLife)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife (100% Thịt & Trứng)',
    brand: 'MEATDeli',
    currentStock: 22,
    minimumStock: 40,
    unitCost: 155000,
    batchNumber: 'LOT-MML-SUON-901',
    expiryDate: '2026-09-12',
    status: 'LOW',
    updatedAt: `${today}T06:30:00.000Z`,
  },
  {
    id: 'inv_mml_02',
    sku: 'MML-BACHI-HEO',
    name: 'Thịt Ba Chỉ Heo MEATDeli Chuẩn Mát (MML)',
    category: 'Thực phẩm tươi sống',
    unit: 'Kg',
    supplier: 'MML (Masan MEATLife)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife (100% Thịt & Trứng)',
    brand: 'MEATDeli',
    currentStock: 35,
    minimumStock: 30,
    unitCost: 148000,
    batchNumber: 'LOT-MML-BACHI-882',
    expiryDate: '2026-09-13',
    status: 'OK',
    updatedAt: `${today}T06:30:00.000Z`,
  },
  {
    id: 'inv_mml_03',
    sku: 'MML-NAC-XAY',
    name: 'Thịt Nạc Dăm Xay MEATDeli (MML)',
    category: 'Thực phẩm tươi sống',
    unit: 'Kg',
    supplier: 'MML (Masan MEATLife)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife (100% Thịt & Trứng)',
    brand: 'MEATDeli',
    currentStock: 18,
    minimumStock: 25,
    unitCost: 135000,
    batchNumber: 'LOT-MML-XAY-771',
    expiryDate: '2026-09-11',
    status: 'LOW',
    updatedAt: `${today}T06:30:00.000Z`,
  },
  {
    id: 'inv_mml_04',
    sku: 'MML-GA-SACH',
    name: 'Thịt Gà Tươi Sạch Thảo Mộc MML (MML)',
    category: 'Thực phẩm tươi sống',
    unit: 'Kg',
    supplier: 'MML (Masan MEATLife)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife (100% Thịt & Trứng)',
    brand: 'Masan MEATLife',
    currentStock: 40,
    minimumStock: 30,
    unitCost: 92000,
    batchNumber: 'LOT-MML-GA-312',
    expiryDate: '2026-09-12',
    status: 'OK',
    updatedAt: `${today}T06:30:00.000Z`,
  },
  {
    id: 'inv_mml_05',
    sku: 'MML-TRUNG-GA',
    name: 'Trứng Gà Tươi Tiệt Trùng MML (MML)',
    category: 'Thực phẩm tươi sống',
    unit: 'Quả',
    supplier: 'MML (Masan MEATLife)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife (100% Thịt & Trứng)',
    brand: 'MML Egg Farm',
    currentStock: 65,
    minimumStock: 120,
    unitCost: 3500,
    batchNumber: 'LOT-MML-EGG-991',
    expiryDate: '2026-09-28',
    status: 'LOW',
    updatedAt: `${today}T06:30:00.000Z`,
  },

  // 2. Gia vị, Nước tương, Tương ớt: 100% từ CHIN-SU / Masan Consumer (Masan Group)
  {
    id: 'inv_cs_01',
    sku: 'CS-NUOC-TUONG',
    name: 'Nước Tương CHIN-SU Nấm Shiitake Tuyệt Đỉnh (Masan Group)',
    category: 'Gia vị & Khô',
    unit: 'Lít',
    supplier: 'CHIN-SU / Masan Consumer',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer (100% Gia Vị & Nước Tương)',
    brand: 'CHIN-SU',
    currentStock: 48,
    minimumStock: 20,
    unitCost: 38000,
    batchNumber: 'LOT-CS-SOY-2026',
    expiryDate: '2027-08-30',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
  {
    id: 'inv_cs_02',
    sku: 'CS-TUONG-OT',
    name: 'Tương Ớt CHIN-SU Cay Nồng Thượng Hạng (Masan Group)',
    category: 'Gia vị & Khô',
    unit: 'Chai (1kg)',
    supplier: 'CHIN-SU / Masan Consumer',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer (100% Gia Vị & Nước Tương)',
    brand: 'CHIN-SU',
    currentStock: 35,
    minimumStock: 15,
    unitCost: 45000,
    batchNumber: 'LOT-CS-CHILI-102',
    expiryDate: '2027-06-30',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
  {
    id: 'inv_cs_03',
    sku: 'CS-NUOC-MAM',
    name: 'Nước Mắm Nam Ngư Cá Hồi Đệ Nhất (Masan Group)',
    category: 'Gia vị & Khô',
    unit: 'Lít',
    supplier: 'CHIN-SU / Masan Consumer',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer (100% Gia Vị & Nước Tương)',
    brand: 'Nam Ngư - Masan',
    currentStock: 50,
    minimumStock: 25,
    unitCost: 52000,
    batchNumber: 'LOT-NN-MAM-772',
    expiryDate: '2027-10-15',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
  {
    id: 'inv_cs_04',
    sku: 'CS-HAT-NEM',
    name: 'Hạt Nêm CHIN-SU Tôm Thịt Ngọt Thanh (Masan Group)',
    category: 'Gia vị & Khô',
    unit: 'Kg',
    supplier: 'CHIN-SU / Masan Consumer',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer (100% Gia Vị & Nước Tương)',
    brand: 'CHIN-SU',
    currentStock: 25,
    minimumStock: 15,
    unitCost: 78000,
    batchNumber: 'LOT-CS-NEM-551',
    expiryDate: '2027-09-20',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },

  // 3. Rau củ quả: 100% từ WinEco (Nông Trường Công Nghệ Cao WinEco)
  {
    id: 'inv_we_01',
    sku: 'WE-RAU-CAI',
    name: 'Rau Cải Xanh Thủy Canh WinEco (100% VietGAP)',
    category: 'Rau củ quả',
    unit: 'Kg',
    supplier: 'WinEco (Nông Trường Công Nghệ Cao Masan)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco (100% Rau Củ Quả Nông Trường Masan)',
    brand: 'WinEco',
    currentStock: 14,
    minimumStock: 30,
    unitCost: 28000,
    batchNumber: 'LOT-WE-CAI-441',
    expiryDate: '2026-09-10',
    status: 'LOW',
    updatedAt: `${today}T06:00:00.000Z`,
  },
  {
    id: 'inv_we_02',
    sku: 'WE-XA-LACH',
    name: 'Xà Lách Lô Lô Xanh Thủy Canh WinEco',
    category: 'Rau củ quả',
    unit: 'Kg',
    supplier: 'WinEco (Nông Trường Công Nghệ Cao Masan)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco (100% Rau Củ Quả Nông Trường Masan)',
    brand: 'WinEco',
    currentStock: 18,
    minimumStock: 20,
    unitCost: 35000,
    batchNumber: 'LOT-WE-SALAD-202',
    expiryDate: '2026-09-10',
    status: 'LOW',
    updatedAt: `${today}T06:00:00.000Z`,
  },
  {
    id: 'inv_we_03',
    sku: 'WE-DUA-LEO',
    name: 'Dưa Leo Trái Dài WinEco Chuẩn VietGAP',
    category: 'Rau củ quả',
    unit: 'Kg',
    supplier: 'WinEco (Nông Trường Công Nghệ Cao Masan)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco (100% Rau Củ Quả Nông Trường Masan)',
    brand: 'WinEco',
    currentStock: 25,
    minimumStock: 20,
    unitCost: 22000,
    batchNumber: 'LOT-WE-CUCUMBER-11',
    expiryDate: '2026-09-12',
    status: 'OK',
    updatedAt: `${today}T06:00:00.000Z`,
  },
  {
    id: 'inv_we_04',
    sku: 'WE-CA-CHUA',
    name: 'Cà Chua Tươi Công Nghệ Cao WinEco',
    category: 'Rau củ quả',
    unit: 'Kg',
    supplier: 'WinEco (Nông Trường Công Nghệ Cao Masan)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco (100% Rau Củ Quả Nông Trường Masan)',
    brand: 'WinEco',
    currentStock: 30,
    minimumStock: 20,
    unitCost: 32000,
    batchNumber: 'LOT-WE-TOMATO-83',
    expiryDate: '2026-09-14',
    status: 'OK',
    updatedAt: `${today}T06:00:00.000Z`,
  },
  {
    id: 'inv_we_05',
    sku: 'WE-CA-ROT',
    name: 'Cà Rốt & Củ Quả Nông Trường WinEco',
    category: 'Rau củ quả',
    unit: 'Kg',
    supplier: 'WinEco (Nông Trường Công Nghệ Cao Masan)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco (100% Rau Củ Quả Nông Trường Masan)',
    brand: 'WinEco',
    currentStock: 32,
    minimumStock: 25,
    unitCost: 26000,
    batchNumber: 'LOT-WE-CARROT-99',
    expiryDate: '2026-09-18',
    status: 'OK',
    updatedAt: `${today}T06:00:00.000Z`,
  },

  // 4. Gạo và thực phẩm khô: 100% từ WinCommerce (WinMart / Masan Group)
  {
    id: 'inv_wcm_01',
    sku: 'WCM-GAO-ST25',
    name: 'Gạo Thượng Hạng Ngọc Nương ST25 WinCommerce',
    category: 'Gia vị & Khô',
    unit: 'Kg',
    supplier: 'WinCommerce (WinMart / Masan Group)',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (100% Gạo & Hàng Khô WinMart)',
    brand: 'Ngọc Nương WinCommerce',
    currentStock: 320,
    minimumStock: 100,
    unitCost: 33000,
    batchNumber: 'LOT-WCM-ST25-08',
    expiryDate: '2026-12-31',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
  {
    id: 'inv_wcm_02',
    sku: 'WCM-DAU-AN',
    name: 'Dầu Ăn Thực Vật Cao Cấp WinCommerce Phân Phối (Can 5L)',
    category: 'Gia vị & Khô',
    unit: 'Can',
    supplier: 'WinCommerce (WinMart / Masan Group)',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (100% Gạo & Hàng Khô WinMart)',
    brand: 'WinMart Selection',
    currentStock: 18,
    minimumStock: 10,
    unitCost: 250000,
    batchNumber: 'LOT-WCM-OIL-10',
    expiryDate: '2027-06-30',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
  {
    id: 'inv_wcm_03',
    sku: 'WCM-NAM-HUONG',
    name: 'Nấm Hương Khô Rừng Tây Bắc WinCommerce',
    category: 'Gia vị & Khô',
    unit: 'Kg',
    supplier: 'WinCommerce (WinMart / Masan Group)',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (100% Gạo & Hàng Khô WinMart)',
    brand: 'WinMart Selection',
    currentStock: 12,
    minimumStock: 8,
    unitCost: 310000,
    batchNumber: 'LOT-WCM-MUSHROOM-4',
    expiryDate: '2027-05-30',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
  {
    id: 'inv_wcm_04',
    sku: 'WCM-DAU-HU',
    name: 'Đậu Hũ Tươi Sạch Hữu Cơ WinCommerce',
    category: 'Thực phẩm tươi sống',
    unit: 'Bìa',
    supplier: 'WinCommerce (WinMart / Masan Group)',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (100% Gạo & Hàng Khô WinMart)',
    brand: 'WinMart Fresh',
    currentStock: 65,
    minimumStock: 40,
    unitCost: 12000,
    batchNumber: 'LOT-WCM-TOFU-88',
    expiryDate: '2026-09-12',
    status: 'OK',
    updatedAt: `${today}T07:00:00.000Z`,
  },
];

// Bill of Materials (BOM) / Recipe Definition per Portion
export const dishRecipes: DishIngredientRecipe[] = [
  // dish_1: Cơm Sườn Nướng Mật Ong Rừng
  {
    dishId: 'dish_1',
    dishName: 'Cơm Sườn Nướng Mật Ong Rừng',
    inventoryItemId: 'inv_mml_01',
    ingredientName: 'Sườn Heo MEATDeli Chuẩn Mát (MML)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife',
    quantityPerPortion: 0.20,
    unit: 'Kg',
  },
  {
    dishId: 'dish_1',
    dishName: 'Cơm Sườn Nướng Mật Ong Rừng',
    inventoryItemId: 'inv_wcm_01',
    ingredientName: 'Gạo Thượng Hạng Ngọc Nương ST25 WinCommerce',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (WinMart)',
    quantityPerPortion: 0.15,
    unit: 'Kg',
  },
  {
    dishId: 'dish_1',
    dishName: 'Cơm Sườn Nướng Mật Ong Rừng',
    inventoryItemId: 'inv_cs_01',
    ingredientName: 'Nước Tương CHIN-SU Nấm Shiitake Tuyệt Đỉnh (Masan Group)',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer',
    quantityPerPortion: 0.02,
    unit: 'Lít',
  },
  {
    dishId: 'dish_1',
    dishName: 'Cơm Sườn Nướng Mật Ong Rừng',
    inventoryItemId: 'inv_we_03',
    ingredientName: 'Dưa Leo Trái Dài WinEco Chuẩn VietGAP',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco Nông Trường',
    quantityPerPortion: 0.08,
    unit: 'Kg',
  },

  // dish_2: Cá Hồi / Ba Chỉ Heo Kho Trứng MML
  {
    dishId: 'dish_2',
    dishName: 'Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo',
    inventoryItemId: 'inv_mml_02',
    ingredientName: 'Thịt Ba Chỉ Heo MEATDeli Chuẩn Mát (MML)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife',
    quantityPerPortion: 0.18,
    unit: 'Kg',
  },
  {
    dishId: 'dish_2',
    dishName: 'Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo',
    inventoryItemId: 'inv_mml_05',
    ingredientName: 'Trứng Gà Tươi Tiệt Trùng MML (MML)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife',
    quantityPerPortion: 1,
    unit: 'Quả',
  },
  {
    dishId: 'dish_2',
    dishName: 'Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo',
    inventoryItemId: 'inv_cs_03',
    ingredientName: 'Nước Mắm Nam Ngư Cá Hồi Đệ Nhất (Masan Group)',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer',
    quantityPerPortion: 0.02,
    unit: 'Lít',
  },
  {
    dishId: 'dish_2',
    dishName: 'Cá Hồi Na Uy Áp Chảo Sốt Chanh Leo',
    inventoryItemId: 'inv_wcm_01',
    ingredientName: 'Gạo Thượng Hạng Ngọc Nương ST25 WinCommerce',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (WinMart)',
    quantityPerPortion: 0.15,
    unit: 'Kg',
  },

  // dish_3: Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)
  {
    dishId: 'dish_3',
    dishName: 'Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)',
    inventoryItemId: 'inv_wcm_04',
    ingredientName: 'Đậu Hũ Tươi Sạch Hữu Cơ WinCommerce',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (WinMart)',
    quantityPerPortion: 1,
    unit: 'Bìa',
  },
  {
    dishId: 'dish_3',
    dishName: 'Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)',
    inventoryItemId: 'inv_wcm_03',
    ingredientName: 'Nấm Hương Khô Rừng Tây Bắc WinCommerce',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (WinMart)',
    quantityPerPortion: 0.04,
    unit: 'Kg',
  },
  {
    dishId: 'dish_3',
    dishName: 'Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)',
    inventoryItemId: 'inv_cs_01',
    ingredientName: 'Nước Tương CHIN-SU Nấm Shiitake Tuyệt Đỉnh (Masan Group)',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer',
    quantityPerPortion: 0.03,
    unit: 'Lít',
  },
  {
    dishId: 'dish_3',
    dishName: 'Đậu Phụ Hữu Cơ Sốt Nấm Đông Cô (Món Chay)',
    inventoryItemId: 'inv_we_01',
    ingredientName: 'Rau Cải Xanh Thủy Canh WinEco (100% VietGAP)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco Nông Trường',
    quantityPerPortion: 0.10,
    unit: 'Kg',
  },

  // dish_4: Gà Ta Kho Gừng Lá Chanh
  {
    dishId: 'dish_4',
    dishName: 'Gà Ta Kho Gừng Lá Chanh',
    inventoryItemId: 'inv_mml_04',
    ingredientName: 'Thịt Gà Tươi Sạch Thảo Mộc MML (MML)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife',
    quantityPerPortion: 0.22,
    unit: 'Kg',
  },
  {
    dishId: 'dish_4',
    dishName: 'Gà Ta Kho Gừng Lá Chanh',
    inventoryItemId: 'inv_cs_04',
    ingredientName: 'Hạt Nêm CHIN-SU Tôm Thịt Ngọt Thanh (Masan Group)',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer',
    quantityPerPortion: 0.015,
    unit: 'Kg',
  },
  {
    dishId: 'dish_4',
    dishName: 'Gà Ta Kho Gừng Lá Chanh',
    inventoryItemId: 'inv_cs_03',
    ingredientName: 'Nước Mắm Nam Ngư Cá Hồi Đệ Nhất (Masan Group)',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer',
    quantityPerPortion: 0.02,
    unit: 'Lít',
  },

  // dish_5: Canh Chua Cá Bông Lau Bạc Hà / Canh Cải Thịt Bằm
  {
    dishId: 'dish_5',
    dishName: 'Canh Chua Cá Bông Lau Bạc Hà',
    inventoryItemId: 'inv_we_01',
    ingredientName: 'Rau Cải Xanh Thủy Canh WinEco (100% VietGAP)',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco Nông Trường',
    quantityPerPortion: 0.15,
    unit: 'Kg',
  },
  {
    dishId: 'dish_5',
    dishName: 'Canh Chua Cá Bông Lau Bạc Hà',
    inventoryItemId: 'inv_mml_03',
    ingredientName: 'Thịt Nạc Dăm Xay MEATDeli (MML)',
    masanSupplier: 'MML',
    masanSupplierName: 'MML - Masan MEATLife',
    quantityPerPortion: 0.06,
    unit: 'Kg',
  },
  {
    dishId: 'dish_5',
    dishName: 'Canh Chua Cá Bông Lau Bạc Hà',
    inventoryItemId: 'inv_cs_04',
    ingredientName: 'Hạt Nêm CHIN-SU Tôm Thịt Ngọt Thanh (Masan Group)',
    masanSupplier: 'CHIN_SU',
    masanSupplierName: 'CHIN-SU / Masan Consumer',
    quantityPerPortion: 0.01,
    unit: 'Kg',
  },

  // dish_6: Canh Hạt Sen Táo Đỏ Nấm Hương (Chay)
  {
    dishId: 'dish_6',
    dishName: 'Canh Hạt Sen Táo Đỏ Nấm Hương (Chay)',
    inventoryItemId: 'inv_wcm_03',
    ingredientName: 'Nấm Hương Khô Rừng Tây Bắc WinCommerce',
    masanSupplier: 'WINCOMMERCE',
    masanSupplierName: 'WinCommerce (WinMart)',
    quantityPerPortion: 0.03,
    unit: 'Kg',
  },
  {
    dishId: 'dish_6',
    dishName: 'Canh Hạt Sen Táo Đỏ Nấm Hương (Chay)',
    inventoryItemId: 'inv_we_05',
    ingredientName: 'Cà Rốt & Củ Quả Nông Trường WinEco',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco Nông Trường',
    quantityPerPortion: 0.06,
    unit: 'Kg',
  },

  // dish_7: Chè Long Nhãn Hạt Sen Tuyết Giáp
  {
    dishId: 'dish_7',
    dishName: 'Chè Long Nhãn Hạt Sen Tuyết Giáp',
    inventoryItemId: 'inv_we_03',
    ingredientName: 'Dưa Leo Trái Dài WinEco Chuẩn VietGAP',
    masanSupplier: 'WINECO',
    masanSupplierName: 'WinEco Nông Trường',
    quantityPerPortion: 0.05,
    unit: 'Kg',
  },
];

// Masan Purchase Orders Store
export const masanPurchaseOrders: MasanPurchaseOrder[] = [
  {
    id: 'po_001',
    poCode: 'PO-MML-20260907-01',
    supplier: 'MML',
    supplierName: 'MML (Masan MEATLife)',
    forMealDate: today,
    createdAt: `${today}T07:15:00.000Z`,
    status: 'APPROVED',
    notes: 'Đơn hàng bổ sung sườn heo và trứng gà sạch phục vụ ca ăn trưa trụ sở chính',
    items: [
      {
        inventoryItemId: 'inv_mml_01',
        name: 'Sườn Heo MEATDeli Chuẩn Mát (MML)',
        unit: 'Kg',
        requiredQty: 35,
        purchaseQty: 20,
        unitPrice: 155000,
        subtotal: 3100000,
      },
      {
        inventoryItemId: 'inv_mml_05',
        name: 'Trứng Gà Tươi Tiệt Trùng MML (MML)',
        unit: 'Quả',
        requiredQty: 120,
        purchaseQty: 60,
        unitPrice: 3500,
        subtotal: 210000,
      },
    ],
    totalAmount: 3310000,
  },
  {
    id: 'po_002',
    poCode: 'PO-WINECO-20260907-01',
    supplier: 'WINECO',
    supplierName: 'WinEco (Nông Trường Công Nghệ Cao Masan)',
    forMealDate: today,
    createdAt: `${today}T07:20:00.000Z`,
    status: 'APPROVED',
    notes: 'Nhập rau củ quả thủy canh WinEco tiêu chuẩn VietGAP thu hoạch sáng sớm',
    items: [
      {
        inventoryItemId: 'inv_we_01',
        name: 'Rau Cải Xanh Thủy Canh WinEco (100% VietGAP)',
        unit: 'Kg',
        requiredQty: 30,
        purchaseQty: 20,
        unitPrice: 28000,
        subtotal: 560000,
      },
    ],
    totalAmount: 560000,
  },
];

// Inventory Transactions Store
export const inventoryTransactions: InventoryTransaction[] = [
  {
    id: 'inv_tx_001',
    inventoryItemId: 'inv_01',
    inventoryItemName: 'Gạo ST25 Sóc Trăng Thượng Hạng',
    type: 'IN',
    quantity: 200,
    reason: 'Nhập kho định kỳ tuần 36 theo hợp đồng cung ứng lương thực',
    performedByUserId: 'usr_chef',
    performedByName: 'Lê Văn Bếp Trưởng',
    createdAt: `${today}T06:30:00.000Z`,
    balanceAfter: 350,
  },
  {
    id: 'inv_tx_002',
    inventoryItemId: 'inv_02',
    inventoryItemName: 'Sườn Heo Sạch C.P Chuẩn VietGAP',
    type: 'OUT',
    quantity: -30,
    reason: 'Xuất bếp nấu Ca B cho 120 suất cơm sườn mật ong',
    performedByUserId: 'usr_chef',
    performedByName: 'Lê Văn Bếp Trưởng',
    createdAt: `${today}T08:30:00.000Z`,
    balanceAfter: 45,
  },
];

// QR Nonce cache for anti-replay verification
export const usedQrNonces = new Set<string>();

// Audit Logs Store
export const auditLogs: AuditLog[] = [
  {
    id: 'audit_001',
    actorUserId: 'usr_admin',
    actorName: 'Nguyễn Văn Quản Trị',
    action: 'SYSTEM_BOOTSTRAP',
    resourceType: 'SYSTEM_CONFIG',
    resourceId: 'SYS_01',
    newValue: 'Khởi tạo hệ thống quản lý suất ăn doanh nghiệp với các ca Sáng, Trưa, Tối, Đêm',
    ipAddress: '10.0.4.1',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    requestId: 'req_init_001',
    createdAt: `${today}T06:00:00.000Z`,
  },
  {
    id: 'audit_002',
    actorUserId: 'usr_chef',
    actorName: 'Lê Văn Bếp Trưởng',
    action: 'MENU_SUBMIT',
    resourceType: 'MENU',
    resourceId: 'menu_today_lunch',
    oldValue: 'DRAFT',
    newValue: 'PENDING_APPROVAL',
    ipAddress: '10.0.4.15',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    requestId: 'req_menu_002',
    createdAt: `${today}T07:45:00.000Z`,
  },
  {
    id: 'audit_003',
    actorUserId: 'usr_hr',
    actorName: 'Trần Thị Nhân Sự',
    action: 'MENU_APPROVE',
    resourceType: 'MENU',
    resourceId: 'menu_today_lunch',
    oldValue: 'PENDING_APPROVAL',
    newValue: 'APPROVED & PUBLISHED',
    ipAddress: '10.0.4.22',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    requestId: 'req_menu_003',
    createdAt: `${today}T08:00:00.000Z`,
  },
];

// Helper to log audit actions securely
export function addAuditLog(entry: Omit<AuditLog, 'id' | 'createdAt'>): AuditLog {
  const log: AuditLog = {
    ...entry,
    id: generateId('audit'),
    createdAt: new Date().toISOString(),
  };
  auditLogs.unshift(log); // newest first
  return log;
}
